   
--------------------------------------------------------
--  create sequences
--------------------------------------------------------  

CREATE SEQUENCE  "SEQ_SHOP_ID"  MINVALUE 1 MAXVALUE 10000000 INCREMENT BY 1 START WITH 400 NOCACHE ORDER  NOCYCLE ;
CREATE SEQUENCE  "SEQ_FOOD_ID"  MINVALUE 1 MAXVALUE 10000000 INCREMENT BY 1 START WITH 400 NOCACHE ORDER  NOCYCLE ;
CREATE SEQUENCE  "SEQ_REVIEW_ID"  MINVALUE 1 MAXVALUE 10000000 INCREMENT BY 1 START WITH 1 NOCACHE ORDER  NOCYCLE ;
CREATE SEQUENCE  "SEQ_REVIEW_IMAGE_ID"  MINVALUE 1 MAXVALUE 10000000 INCREMENT BY 1 START WITH 1 NOCACHE ORDER  NOCYCLE ;
CREATE SEQUENCE  "SEQ_REVIEW_REPLY_ID"  MINVALUE 1 MAXVALUE 10000000 INCREMENT BY 1 START WITH 1 NOCACHE ORDER  NOCYCLE ;
CREATE SEQUENCE  "SEQ_J_ORDER_ID"  MINVALUE 1 MAXVALUE 10000000 INCREMENT BY 1 START WITH 1 NOCACHE ORDER  NOCYCLE ;
CREATE SEQUENCE  "SEQ_J_REVIEW_ID"  MINVALUE 1 MAXVALUE 10000000 INCREMENT BY 1 START WITH 1 NOCACHE ORDER  NOCYCLE ;
CREATE SEQUENCE  "SEQ_J_REVIEW_IMAGE_ID"  MINVALUE 1 MAXVALUE 10000000 INCREMENT BY 1 START WITH 1 NOCACHE ORDER  NOCYCLE ;


--------------------------------------------------------
--  create triggers
--------------------------------------------------------  
CREATE OR REPLACE TRIGGER TRI_SHOP_shop_id BEFORE INSERT ON SHOP
FOR EACH ROW
BEGIN
	SELECT SEQ_SHOP_ID.nextval
	INTO :new.shop_id
	FROM dual;
END;


CREATE OR REPLACE TRIGGER TRI_FOOD_food_id BEFORE INSERT ON FOOD
FOR EACH ROW
BEGIN
	SELECT SEQ_FOOD_ID.nextval
	INTO :new.food_id
	FROM dual;
END;


CREATE OR REPLACE TRIGGER TRI_J_ORDER_order_id BEFORE INSERT ON J_ORDER
FOR EACH ROW
BEGIN
	SELECT SEQ_J_ORDER_ID.nextval
	INTO :new.order_id
	FROM dual;
END;


CREATE OR REPLACE TRIGGER TRI_J_REVIEW_review_id BEFORE INSERT ON J_REVIEW
FOR EACH ROW
BEGIN
	SELECT SEQ_J_REVIEW_ID.nextval
	INTO :new.review_id
	FROM dual;
END;

CREATE OR REPLACE TRIGGER TRI_J_REVIEW_IMAGE_image_id BEFORE INSERT ON J_REVIEW_IMAGE
FOR EACH ROW
BEGIN
	SELECT SEQ_J_REVIEW_IMAGE_ID.nextval
	INTO :new.image_id
	FROM dual;
END;

select * from shop where shop_id=401;

select * from member;